DEBUG = y
KMOD= madbus
SRCS= madbus.h ../../include/madbusioctls.h ../../include/maddefs.h ../../include/madkonsts.h madbusmain.c mbdevthread.c
CFLAGS= -I$S/compat/linuxkpi/common/include
.include <bsd.kmod.mk>


